In [1]:
import numpy as np

In [6]:
# Создайте массив Numpy под названием a размером 5x2
A = np.array([[1,6],
              [2,8],
              [3,11],
              [3,10],
              [1,7]])

In [47]:
A

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [13]:
A.shape

(5, 2)

In [42]:
# Задание 1. Затем найдите среднее значение по каждому признаку, 
# используя метод mean массива Numpy. Результат запишите в массив mean_a, 
# в нем должно быть 2 элемента. 
mean_A = A.mean(axis=0)
mean_A

array([2. , 8.4])

In [45]:
# Задание 2. Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, 
# содержащиеся в массиве mean_a. 
# Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.
a_centered = A - mean_A
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [48]:
a_centered.shape

(5, 2)

In [28]:
# Задание 3. Найдите скалярное произведение столбцов массива a_centered. 
# В результате должна получиться величина a_centered_sp. 
a_t = a_centered.T
a0 = a_t[0]
a1 = a_t[1]
a_centered_sp = a0.dot(a1)
a_centered_sp

8.0

In [50]:
# Задание 3. Вариант решения 2
a_centered_sp = a0 @ a1
a_centered_sp

8.0

In [49]:
# Задание 4*. В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом - 
# с помощью функции np.cov. В качестве аргумента m функция np.cov должна принимать транспонированный массив “a”. 
# В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение ковариации 
# будет равно элементу в строке с индексом 0 и столбце с индексом 1.
np.cov(A.T)

array([[1. , 2. ],
       [2. , 4.3]])