## Тема: Библиотеки Python для Data Science
### Урок 1. Часть 1. Библиотека Numpy

### Задание 1. 

Импортируйте библиотеку Numpy и дайте ей псевдоним np.
Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение. Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемента.

In [1]:
import numpy as np

In [53]:
A = np.array([[1,6],
              [2,8],
              [3,11],
              [3,10],
              [1,7]])
A

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [13]:
A.shape

(5, 2)

In [42]:
mean_A = A.mean(axis=0)
mean_A

array([2. , 8.4])

### Задание 2. 

Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, 
содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. 
Получившийся массив должен иметь размер 5x2.

In [45]:
a_centered = A - mean_A
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [48]:
a_centered.shape

(5, 2)

### Задание 3. 

Найдите скалярное произведение столбцов массива a_centered. 
В результате должна получиться величина a_centered_sp. 
Затем поделите a_centered_sp на N-1, где N - число наблюдений.

In [57]:
# Вариант решения 1
a_t = a_centered.T
a0 = a_t[0]
a1 = a_t[1]
a_centered_sp = a0.dot(a1)
a_centered_sp/(a_centered.shape[0]-1)

2.0

In [58]:
# Вариант решения 2
a_t = a_centered.T
a0 = a_t[0]
a1 = a_t[1]
a_centered_sp = a0 @ a1
a_centered_sp/(a_centered.shape[0]-1)

2.0

### Задание 4*. 

В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом - 
с помощью функции np.cov. В качестве аргумента m функция np.cov должна принимать транспонированный массив “a”. 
В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение ковариации 
будет равно элементу в строке с индексом 0 и столбце с индексом 1.

In [49]:
np.cov(A.T)

array([[1. , 2. ],
       [2. , 4.3]])